config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'
  root 'posts#index'

  resources :posts

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  delete 'logout' => 'sessions#destroy'
  post 'login' => 'sessions#create'
  get 'stories' => 'posts#postsJS'
  get '/about' => 'about#index'
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/geojson_builder.rb
class GeojsonBuilder
  def build_event(event, geojson)
    geojson << {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [event.longitude, event.latitude] # this part is tricky
      },
      properties: {
        title: event.title,
        address: event.address,
        :"marker-color" => "#FFFFFF",
        :"marker-symbol" => "circle",
        :"marker-size" => "medium",
      }
    }
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  validates :body, presence: true,
                    length: { minimum: 3, maximum: 300 }
  validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  before_save { self.email = email.downcase }
  before_save { self.username = username.downcase }

  validates :username,
            presence: true,
            length: { minimum: 2, maximum: 15},
            uniqueness: true

  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i.freeze

  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: VALID_EMAIL_REGEX }

  validates :password,
            presence: true,
            length: { minimum: 6 }

  has_secure_password

  row_to_json(record [, pretty_bool])

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    redirect_to login_path unless logged_in?
  end

end

app/controllers/events_controller.rb
class SpotsController < ApplicationController
	before_action :find_spot, only: [:show, :edit, :update, :destroy]

	def index
	end

	def map
		@spot = Spot.new

		@spots = Spot.all
		@geojson = Array.new

        @spots.each do |spot|
          @geojson << {
            type: 'Feature',
            geometry: {
              type: 'Point',
              coordinates: [spot.longitude, spot.latitude]
          },
            properties: {
              state: spot.state,
              address: spot.address,
              description: "<strong>TEST</strong>",
              :'marker-color' => '#00607d',
              :'marker-symbol' => 'circle',
              :'marker-size' => 'medium'
            }
          }
        end

        respond_to do |format|
          format.html
          format.json { render json: @geojson }  # respond with the created JSON object
        end


	end

	def create
		@spot = Spot.new(spot_params)
		if @spot.save
			redirect_to map_path
		else
			render 'form'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @spot.update(spot_params)
			redirect_to @spot
		else
			render 'edit'
		end
	end

	def destroy
		@spot.destroy
		redirect_to root_path
	end

	private

	def spot_params
		params.require(:spot).permit(:street,:number,:city,:state,:country, :address)
	end

	def find_spot
		@spot = Spot.find(params[:id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user
  before_action :correct_user, only:[:edit, :update, :destroy]
  helper_method :time_calculation

  def index
    sentimentbar
    @posts = []
    @all_posts = Post.all.order(created_at: :desc)
    @all_posts.each do |p|
    @posts << p if (Time.new - p.created_at) < 86400
    gon.preference = @all_posts
    @sentiment_store = $analyser.score @all_posts
    tempHash = @sentiment_store.to_json
      File.open("sentiment.json","a") do |f|
        f.write(JSON.pretty_generate(tempHash))
      end
    end
  end

  def sentimentbar
    positive = 0.00
    negative = 0.00
    neutral = 0.00
    i = 0
    all_body = Post.find_by_sql("SELECT body FROM posts WHERE choice = 'Emotion';")
    @sentiment_word_store = []
    while i < all_body.length
      body = all_body[i].body
      mark = $analyser.sentiment body
      @sentiment_word_store.push(mark)
      i += 1
    end
    j = 0
    while j < @sentiment_word_store.length
      if @sentiment_word_store[j] == :positive
        positive += 1
      elsif @sentiment_word_store[j] == :negative
        negative += 1
      else
        neutral += 1
      end
      j += 1
    end
    total = (positive + negative + neutral)
    @positive_sent = ((positive*100)/total).round
    @neutral_sent = ((neutral*100)/total).round
    @negative_sent = ((negative*100)/total).round
  end

  def postsJS
    render json: { status: 200, all_stories: Post.all }
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = "Your post has been added"
      redirect_to posts_path
    else
      render 'new'
    end
  end


  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "Your posts has been updated"
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = 'Your post has been deleted'
    redirect_to posts_path
  end


  def time_calculation(created_at_time, time_now = Time.new)
  time_difference_in_sec = time_now - created_at_time
  if time_difference_in_sec < 60
    "#{time_difference_in_sec.to_i} seconds ago"
  elsif time_difference_in_sec < 3600
    "#{(time_difference_in_sec / 60).to_i} minutes ago"
  else time_difference_in_sec < 86_400
    "#{((time_difference_in_sec / 60) / 60).to_i} hours ago"
  end
end

  private
  def post_params
    params.require(:post).permit(:choice, :body, :latitude, :longitude)
  end
  def correct_user
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:success] = "Welcome #{@user.username}"
      redirect_to posts_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out, bye Felicia"
    redirect_to login_path
  end

end

app/controllers/toggle_controller.rb
class ToggleController < ApplicationController
  def show
    render 'toggle/toggle'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome #{@user.username}"
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    flash[:success] = 'You have been destroyed!'
    redirect_to login_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/toggle_helper.rb
module ToggleHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<body style="color: white">
  <h1 class="text-center display-4">Welcome to tap.me</h1>
    <br>
  <p class="text-center h2">Why tap.me?</p>
    <br>
    <br>
  <p class="text-center">Over 9 Million people experience loneliness in the UK. Research shows
    that loneliness and social isolation are harmful to our health;
    lacking social connections is a comparable risk factor for early death as smoking 15 cigarettes a day,
    and is worse for us than well-known risk factors such as obesity and physical inactivity.
    Loneliness increases the likelihood of mortality by 26%.</p>
    <br>
  <p class="text-center h2">How does tap.me work?</p>
    <br>
    <br>
    <div class="about-container">
      <div class="about-square">
        <span class="oi oi-location" style="font-size: 50px"></span>
        <p>Accept the browser location request</p>
      </div>
      <div class="about-square">
        <span class="oi oi-map" style="font-size: 50px"></span>
        <p>View all the nearby posts on a map</p>
      </div>
      <div class="about-square">
        <span class="oi oi-pencil" style="font-size: 50px"></span>
        <p>Create emotion or action based posts</p>
      </div>
      <div class="about-square">
        <span class="oi oi-person" style="font-size: 50px"></span>
        <p>Connect authentically with people nearby</p>
      </div>
    </div>
      <br>
      <br>
  <p class="text-center h2">The tap.me team</p>
    <br>
    <div class="text-container">
  <a class="text-center team-text" href="https://www.linkedin.com/in/jayda-kadir-73a27075/" target="_blank">Jayda</a>
  <a class="text-center team-text" href="https://www.linkedin.com/in/melanierogan/" target="_blank">Mel</a>
  <a class="text-center team-text" href="https://linkedin.com/in/ollieporter/" target="_blank">Ollie</a>
  <a class="text-center team-text" href="https://www.linkedin.com/in/manisha-patel-627699125/" target="_blank">Manisha</a>
    </div>
   <br>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TapMe</title>
    <%= include_gon %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src='https://api.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.css' rel='stylesheet' />
    <script>
      $(document).ready(function(){
         $('#mood-button').click(function(){
           $('#mood-bar').toggle();
         });
       });
    </script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css" integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous" />
  </head>

  <header>
  <% if logged_in? %>
  <nav class="navbar navbar-expand-lg navbar-light bg-white">

  <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon">
    </span>
  </button>
  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
    <li class="nav-item px-3">
      <%= image_tag('tap_me_logo_p.png', :alt => 'Tap me logo', :style => 'height: 40px') %>
    </li>
    <li class="nav-item px-3 <%= 'active' if current_page? posts_path %>">
      <%= link_to 'Posts', posts_path, :class => "nav-link" %>
    </li>
    <li class="nav-item px-3 <%= 'active' if current_page? about_path %>">
      <%= link_to 'About', about_path, :class => "nav-link" %>
    </li>
    <li class="nav-item dropdown px-2">
      <button onclick="myFunction()" class="dropbtn">Settings ▾</button>
      <div id="myDropdown" class="dropdown-content">
      <%= link_to 'Delete Account', user_path(current_user), class: "nav-link", :style => "color: #f56d74",
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
    </li>
      <% if current_page?(posts_path) %>
    <li class="nav-item px-2">
  <a id="mood-button" class="nav-link pointer">
Today's Mood
</a>
</li>
<% end %>
    <li class="nav-item px-2">
      <%= link_to 'Log Out', logout_path, :class => "nav-link", method: :delete %>
    </li>

  </ul>
  </div>
  </nav>
  <% if current_page?(posts_path) %>
  <section>
  <div id="mood-bar" class= "hidden">
    <div class="sentiment_negative" role="progressbar" style="width: <%= @negative_sent %>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"><strong>😔</strong></div>
    <div class="sentiment_neutral" role="progressbar" style="width: <%= @neutral_sent %>%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"><strong>😐</strong></div>
    <div class="sentiment_positive" role="progressbar" style="width: <%= @positive_sent %>%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"><strong>😊</strong></div>
  </div>
  </section>
  <%= render 'map' %>
  <% end %>
  <% end %>
</header>

  <body>

  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col col-lg">
      </div>
      <div class="col-md-auto">
      <div class="container fluid">
        <div class="container fluid" align="center">
        <img src="https://user-images.githubusercontent.com/16557524/61187400-a2398900-a668-11e9-9855-84c3ded1eee7.png" class="img-fluid" style="align: center;">
      </div>
      <%= yield %>
      </div>
      </div>
      <div class="col col-lg">
      </div>
    </div>
  </div>
  </body>

</html>

app/views/posts/_form.html.erb
<div class="container-fluid">
  <div class="row melcolor">
    <div class="col melcolor">
      <div class="melcolor post-form-align" id="who">
        <div class="post-form">
          <%= form_with(model: @post, local: true) do |form| %>
            <h2 class="text-center">My Post</h2>
            <div class="form-group">
              <%= form.label :choice %><br>
              <%= form.select :choice, options_for_select(['Emotion', 'Action']), {}, { :class => 'form-control col-lg' } %>
            </div>
            <div class="form-group">
              <%= form.label :post %>
              <%= form.text_area :body, class: "form-control", placeholder: "Post" %>
            </div>

            <%= form.hidden_field :latitude ,:id=>"latitude" %>
            <%= form.hidden_field :longitude ,:id=>"longitude" %>

            <script type="text/javascript">
               navigator.geolocation.getCurrentPosition((position) => {
               $('#latitude').attr('value', position.coords.latitude)
               $('#longitude').attr('value', position.coords.longitude)
               $('.submit').css('display', 'block')
               })
            </script>

            <div class="container">
              <div class="row text-center">
                <div class="col-lg">
                  <%= link_to 'Cancel', posts_path, class: "btn btn-secondary" %>
                </div>
                <div class="col-lg submit">
                <%= form.submit 'Save Post', :class => "btn btn-primary" %>
                </div>
              </div>
            </div>
          <% end %>
            <div class="col melcolor">
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_map.html.erb
<div id='map'></div>

<script>
mapboxgl.accessToken = 'pk.eyJ1Ijoicm9nYW5tYyIsImEiOiJjanh6MXAzbmIwNGl2M2xwamJ6Mnh4ZGlyIn0.ci0Fq8hiU-MtsoGWVKt4Qg'
var map = new mapboxgl.Map({
container: 'map',
style: 'mapbox://styles/roganmc/cjxyz43go0h081cpccmtt9bmd',
center: [-0.09875959999999999, 51.5245287],
zoom: 16.15
});
 
map.on('load', function () {
  // Add a layer showing the places.
  $.ajax({
  type: "GET",
  url: "/stories",
  dataType: "json",
  success: function (json) {
    $.each(json.all_stories, function(body, id, address, latitude, longitude){
    
    map.addLayer({
                  "id": JSON.stringify(id.id),
                  "type": "symbol",
                  "source": {
                  "type": "geojson",
                  "data": {
                  "type": "FeatureCollection",
                  "features": [
                    //that's the badger
                  {
                  "type": "Feature",
                  "properties": {
                  "description": JSON.stringify(id.body),
                  "icon": "theatre"
                  },
                  "geometry": {
                  "type": "Point",
                  "coordinates": [id.longitude, id.latitude]
                  }
                  }]
                  }
                  },
                  "layout": {
                  "icon-image": 
                  id.choice,
                  "icon-size": 0.25,
                  "icon-allow-overlap": true
                  }
                  }); 

                    // When a click event occurs on a feature in the places layer, open a popup at the
  // location of the feature, with description HTML from its properties.
  map.on('click', JSON.stringify(id.id), function (e) {
    var coordinates = e.features[0].geometry.coordinates.slice();
    var description = e.features[0].properties.description;
    // Ensure that if the map is zoomed out such that multiple
    // copies of the feature are visible, the popup appears
    // over the copy being pointed to.
    while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
      coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360;
    }
    new mapboxgl.Popup()
      .setLngLat(coordinates)
      .setHTML(description)
      .addTo(map);
  });
  // Change the cursor to a pointer when the mouse is over the places layer.
  map.on('mouseenter', JSON.stringify(id.id), function () {
    map.getCanvas().style.cursor = 'pointer';
  });
  // Change it back to a pointer when it leaves.
  map.on('mouseleave', JSON.stringify(id.id), function () {
    map.getCanvas().style.cursor = '';
  });
  
    });
  },
  error: function(e) {
    console.log("error" +e.message)
  }
});
// Add geolocate control to the map.
map.addControl(new mapboxgl.GeolocateControl({
positionOptions: {
enableHighAccuracy: true
},
trackUserLocation: true
}));
});
</script>

app/views/posts/_sentimentbar.html.erb
<div id="sentiment">
    <div class="sentiment_negative" role="progressbar" style="width: <%= @negative_sent %>%" aria-valuenow="15" aria-valuemin="0" aria-valuemax="100"><strong>😔</strong></div>
    <div class="sentiment_neutral" role="progressbar" style="width: <%= @neutral_sent %>%" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"><strong>😐</strong></div>
    <div class="sentiment_positive" role="progressbar" style="width: <%= @positive_sent %>%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"><strong>😊</strong></div>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">

    $(document).ready(function() {
      $('#mol_toggle').change(function (){
        if(this.checked)
          $('.Emotion').hide() && $('.Action').show();
        else
          $('.Emotion').show() && $('.Action').hide();
      })
    });

    </script>


      <div class="container fluid" align="left">
        <input class="toggle" id="mol_toggle" type="checkbox" />
        <%= link_to '+', new_post_path, class: "btn btn-secondary btn-circle float-right", style: "padding-top: 2px", id: "new_post" %>
      </div>

<br><br><br>
<% @posts.each do |p| %>
<div class="card fluid p-4 <%= p.choice %>">

    <p class="post_username"><%= User.find(p.user_id).username %></p>
    <div class="d-flex justify-content-between">
    <p class="post_choice"><%= p.choice %></p>
    <p class="post_time"><%= time_calculation(p.created_at) %></p>
    </div>
    <p><%= simple_format(p.body, class: 'text-center') %></p>

  <div class="container fluid">
  <figure class="figure">
    <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{p.latitude},#{p.longitude}&markers=#{p.latitude},#{p.longitude}&zoom=17&size=640x200&key=#{ENV['GOOGLE_API_KEY']}",
   class: 'figure-img img-fluid', alt: '#{p.address} on the map'%>

   <figcaption class="figure-caption text-right"><%= truncate(p.address, :length => 80) %></figcaption>
   </figure>
  </div>
  <% if current_user.username == p.user.username %>
  <div class="container">
    <div class="row text-center">
      <div class="col-lg">
      <%= link_to 'Update', edit_post_path(p), :class => "btn btn-tertiary" %>
      </div>
      <div class="col-lg">
      <%= link_to 'Delete', post_path(p), :class => "btn btn-tertiary",
      method: :delete,
      data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </div>
  <% else %>

  <% end %>
</div>
<br class="<%= p.choice %>">
<br class="<%= p.choice %>">
<br class="<%= p.choice %>">
<br class="<%= p.choice %>">
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/test.html.erb
<p> hope this prints the variable here: <%= ENV['GOOGLE_API'] %></p>
  <img src="<%= ENV['GOOGLE_API'] %>">
  <p> hope this shows the variable in the url:</p>
  <img src="https://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=13&size=600x300&maptype=roadmap&markers=color:blue%7Clabel:S%7C40.702147,-74.015794&markers=color:green%7Clabel:G%7C40.711614,-74.012318&markers=color:red%7Clabel:C%7C40.718217,-73.998284&key=<%= ENV['GOOGLE_API'] %>">
  <p> hope this shows the key variable in the url:</p>
  <img src="https://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York,NY&zoom=13&size=600x300&maptype=roadmap&markers=color:blue%7Clabel:S%7C40.702147,-74.015794&markers=color:green%7Clabel:G%7C40.711614,-74.012318&markers=color:red%7Clabel:C%7C40.718217,-73.998284&key=<%= ENV['GOOGLE_API_KEY'] %>">

app/views/users/_map.html.erb
<script src='https://api.mapbox.com/mapbox-gl-js/v0.34.0/mapbox-gl.js'></script>
        <link href='https://api.mapbox.com/mapbox-gl-js/v0.34.0/mapbox-gl.css' rel='stylesheet' />

<script>
mapboxgl.accessToken = 'pk.eyJ1Ijoicm9nYW5tYyIsImEiOiJjanh6MXAzbmIwNGl2M2xwamJ6Mnh4ZGlyIn0.ci0Fq8hiU-MtsoGWVKt4Qg';
 
var map = new mapboxgl.Map({
container: 'map',
style: 'mapbox://styles/mapbox/streets-v11',
center: [-77.04, 38.907],
zoom: 11.15
});
 
map.on('load', function () {
// Add a layer showing the places.
map.addLayer({
"id": "places",
"type": "symbol",
"source": {
"type": "geojson",
"data": {
"type": "FeatureCollection",
"features": [
  //that's the badger
{
"type": "Feature",
"properties": {
"description": "<strong>Make it Mount Pleasant</strong><p><a href=\"http://www.mtpleasantdc.com/makeitmtpleasant\" target=\"_blank\" title=\"Opens in a new window\">Make it Mount Pleasant</a> is a handmade and vintage market and afternoon of live entertainment and kids activities. 12:00-6:00 p.m.</p>",
"icon": "theatre"
},
"geometry": {
"type": "Point",
"coordinates": [-0.082810, 51.562060]
}
}]
}
},
"layout": {
"icon-image": "{icon}-15",
"icon-allow-overlap": true
}
});
// When a click event occurs on a feature in the places layer, open a popup at the
// location of the feature, with description HTML from its properties.
map.on('click', 'places', function (e) {
var coordinates = e.features[0].geometry.coordinates.slice();
var description = e.features[0].properties.description;
 
// Ensure that if the map is zoomed out such that multiple
// copies of the feature are visible, the popup appears
// over the copy being pointed to.
while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360;
}
 
new mapboxgl.Popup()
.setLngLat(coordinates)
.setHTML(description)
.addTo(map);
});
 
// Change the cursor to a pointer when the mouse is over the places layer.
map.on('mouseenter', 'places', function () {
map.getCanvas().style.cursor = 'pointer';
});
 
// Change it back to a pointer when it leaves.
map.on('mouseleave', 'places', function () {
map.getCanvas().style.cursor = '';
});
});
</script>

<div id='map'></div>

app/views/users/edit.html.erb
<h2>Edit user details</h2>
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: "form-control", placeholder: "New Username" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", placeholder: "Enter new email" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "New Password" %>
    </div>
    <%= f.submit 'Confirm', class: "btn btn-outline-light" %>
    
<% end %>

app/views/users/index.html.erb
<div class="container-fluid">
   <div class="row melcolor">
          <div class="col melcolor" >
              <div class="melcolor" id="who" style="width: 60rem;">
                  <div class="login-form" style="padding-top: 50px;">
                      <form action="/login" method="POST">
                        <div class="avatar">
                          </div>
                          <h2></h2>
                          <div class="form-group">
                            <input type="text" class="form-control" name="email" placeholder="Email" required="required">
                          </div>
                      <div class="form-group">
                              <input type="password" class="form-control" name="password" placeholder="Password" required="required">
                          </div>
                          <div class="form-group">
                              <button type="submit" class="btn btn-primary btn-lg btn-block">Sign in</button>
                          </div>
                      </form>
                      <p class="text-center small">Don't have an account? <a href="/signup">Sign up here!</a></p>
                  </div>
              </div>
          </div>
        <div class="col melcolor">
        </div>
      </div>
    </div>

app/views/users/new.html.erb
<div class="container-fluid">
  <div class="row melcolor">
    <div class="col melcolor" >
      <div class="melcolor" id="who">
        <div class="login-form"">
          <%= form_for @user do |f| %>
            <div class="avatar">
            </div>
            <h2></h2>
            <div class="form-group">
              <%= f.label :username %>
              <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
            </div>
            <div class="form-group">
              <%= f.label :email %>
              <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
            </div>
            <div class="form-group">
              <%= f.label :password %>
              <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
            </div>
            <%= f.submit 'Sign Up', class: "btn btn-primary btn-lg btn-block" %>
          <% end %>
            <p class="text-center small">Already have an account? <a href="/login">Log in here!</a></p>
            <div class="col melcolor">
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/testpost.html.erb
<%= render 'map' %>